version: '3.7'

services:
    frontend:
        container_name: admin_react
        build:
            context: ./react-admin
            dockerfile: Dockerfile-frontend
        volumes:
            - frontend_sources:/usr/src/app:rw
        environment:
            - XDEBUG_CONFIG=remote_host=172.0.0.1 remote_enable=on
            - COMPOSER_AUTH=${COMPOSER_AUTH}
            - VIRTUAL_HOST=frontend.micro.test
            - VIRTUAL_PORT=3000
        #ports:
        #    - "81:3000"
        depends_on:
            - backend
        links:
            - backend:admin_api
        env_file:
            - react-admin/.env
        logging:
            driver: "json-file"
            options:
                max-size: "1M"
                max-file: "5"

    backend:
        container_name: admin_api
        build:
            context: ./backend
            dockerfile: Dockerfile-backend
        volumes:
            - backend_sources:/var/www:rw
            - ./backend/docker/vhost.d:/etc/apache2/sites-enabled
        environment:
            - XDEBUG_CONFIG=remote_host=172.0.0.1 remote_enable=on
            - APP_XDEBUG=enabled
            - COMPOSER_AUTH=${COMPOSER_AUTH}
            - VIRTUAL_HOST=backend.micro.test
            - VIRTUAL_PORT=80
        depends_on:
            - db
        links:
            - db:db
            - mail:mail
        env_file:
            - backend/.env
        logging:
            driver: "json-file"
            options:
                max-size: "1M"
                max-file: "5"

    db:
        container_name: admin_db
        image: mysql:8
        command: [mysqld, --default-authentication-plugin=mysql_native_password]
        volumes:
            - database:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: "toor"
            MYSQL_USER: "microservices"
            MYSQL_PASSWORD: "monolith"
            MYSQL_DATABASE: "microservices"
        ports:
            - "3306:3306"

    mail:
        image: djfarrelly/maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        expose:
            - 8080
        environment:
            - VIRTUAL_HOST=mailer.micro.test
            - VIRTUAL_PORT=80

volumes:
    database: ~
    frontend_sources:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/react-admin
    backend_sources:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/backend

networks:
    default:
        external:
            name: nginx-proxy
