POST https://backend.micro.test/api/users
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: application/json

--WebAppBoundary
Content-Disposition: form-data; name="last_name"

test
--WebAppBoundary
Content-Disposition: form-data; name="first_name"

test 2
--WebAppBoundary
Content-Disposition: form-data; name="email"

test-3@yopmail.fr
--WebAppBoundary
Content-Disposition: form-data; name="password"

password
--WebAppBoundary--

